steps:

  - id: "Rodando docker"
    name: 'docker/compose'
    args: ['-f','docker-compose.yaml','up','-d']

  - id: "Rodando phpunit"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','go','test','-v', '-run', 'TestGreetings']