steps:
  - id: "Rodando docker & Tests"
    name: "docker/compose"
    args: ["-f", "docker-compose.yaml", "up", "-d"]

  - id: "Rodando test"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "go", "test", "-v", "-run", "TestGreetings"]

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "deployment.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1"
