  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: desafio-go
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: desafio-go
    template:
      metadata:
        labels:
          app: desafio-go
      spec:
        containers:
        - name: desafio-go
          image: zorobadel/goweb:latest
          ports:
          - containerPort: 8000