apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: desafio-go
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: desafio-go
  targetCPUUtilizationPercentage: 15
